# Generated by Django 3.2.8 on 2021-10-19 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(default='5714', max_length=20)),
                ('street_name', models.CharField(default='Tshega street', max_length=255)),
                ('provice', models.CharField(choices=[('GP', 'Gauteng')], default='GP', max_length=2)),
                ('locality', models.CharField(blank=True, default='soshanguve', max_length=255, null=True)),
                ('municipality', models.CharField(default='Tshwane', max_length=255)),
                ('postal_code', models.CharField(default='0152', max_length=10)),
                ('country', models.CharField(default='South Africa', editable=False, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('RECEIVED', 'RECEIVED')], default='RECEIVED', max_length=9)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accomodations.address')),
                ('application', models.ManyToManyField(related_name='accomodation', to='accomodations.Application')),
                ('likes', models.ManyToManyField(blank=True, related_name='accomodation_likes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
