# Generated by Django 3.2.8 on 2021-10-19 15:14

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='slug',
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
