# Generated by Django 3.2.8 on 2021-10-09 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accomodations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accomodations.address'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='accomodation_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
