# Generated by Django 3.2.8 on 2021-10-19 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0002_auto_20211019_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
