# Generated by Django 3.2.8 on 2021-10-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0003_alter_accomodation_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
