# Generated by Django 3.2.8 on 2021-10-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0004_accomodation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='accomodation',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='application',
            field=models.ManyToManyField(to='accomodations.Application'),
        ),
    ]
