# Generated by Django 3.2.8 on 2021-10-20 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accomodations', '0004_auto_20211020_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='application',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='applied',
            field=models.ManyToManyField(blank=True, related_name='accomodation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='accomodation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='accounts.user', verbose_name='accomodation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
        ),
    ]
