# Generated by Django 3.2.8 on 2021-10-20 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accomodations', '0005_auto_20211020_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='applied',
            field=models.ManyToManyField(blank=True, default=None, related_name='applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('RECEIVED', 'RECEIVED'), ('CANCELLED', 'CANCELLED')], default='RECEIVED', max_length=10),
        ),
    ]
