# Generated by Django 3.2.8 on 2021-10-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0005_auto_20211011_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='application',
            field=models.ManyToManyField(related_name='accomodation', to='accomodations.Application'),
        ),
    ]
