# Generated by Django 3.2.8 on 2021-10-20 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0006_auto_20211020_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='image_1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
