# Generated by Django 3.2.8 on 2021-10-21 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0007_alter_accomodation_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
