# Generated by Django 3.2.8 on 2021-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('fEMALE', 'fEMALE')], default='MALE', max_length=8),
        ),
    ]
