# Generated by Django 3.2.8 on 2021-10-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='admin@localhost.com', max_length=254, verbose_name='Email Address: '),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10, verbose_name='Contact Number: '),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_number',
            field=models.CharField(default='00000000', max_length=8, verbose_name='Student Number: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('fEMALE', 'fEMALE')], default='MALE', max_length=8, verbose_name='Gender'),
        ),
    ]
